In [1]:
import numpy as np

In [6]:
# creating array with arrange function of numpy
a = np.arange(15) # single dimensional
print (a)
a = np.arange(15).reshape(3,5) # multi dimensional
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
# size of array
a.size

15

In [7]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [11]:
y = np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [13]:
print('shape:',x.shape)
print('num of dimensions:',x.ndim)
print('type of data:',x.dtype)
print("Y")
print('shape:',y.shape)
print('num of dimensions:',y.ndim)
print('type of data',y.dtype)

shape: (5,)
num of dimensions: 1
type of data: int32
Y
shape: (2, 3)
num of dimensions: 2
type of data int32


- arange
- linspace
- random.*
- eye
- ones
- zeros

In [18]:
np.set_printoptions(precision=4,suppress=True)

In [19]:
a = np.arange(-10,10,.2)
print(a)

[-10.   -9.8  -9.6  -9.4  -9.2  -9.   -8.8  -8.6  -8.4  -8.2  -8.   -7.8
  -7.6  -7.4  -7.2  -7.   -6.8  -6.6  -6.4  -6.2  -6.   -5.8  -5.6  -5.4
  -5.2  -5.   -4.8  -4.6  -4.4  -4.2  -4.   -3.8  -3.6  -3.4  -3.2  -3.
  -2.8  -2.6  -2.4  -2.2  -2.   -1.8  -1.6  -1.4  -1.2  -1.   -0.8  -0.6
  -0.4  -0.2  -0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8
   2.    2.2   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2
   4.4   4.6   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6
   6.8   7.    7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.
   9.2   9.4   9.6   9.8]


In [20]:
print(a.size)

100


In [21]:
b = np.linspace(0,1,10)
print(b)

[0.     0.1111 0.2222 0.3333 0.4444 0.5556 0.6667 0.7778 0.8889 1.    ]


In [26]:
np.random.random((3,3)) #random values between 0 and 1

array([[0.9079, 0.2193, 0.5795],
       [0.2533, 0.6737, 0.2468],
       [0.8709, 0.7447, 0.7239]])

In [27]:
np.random.randint(1,1000,(3,3)) # random values between start and end

array([[177, 714,  27],
       [425, 434, 852],
       [ 94, 159, 410]])

In [31]:
np.eye(5,dtype=int) # identity matrix
# for rotating use rot(angle)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [29]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Operations
- arithmatic
- statistical
- trignometric
- logical
- slicing
- filtering
- sorting

In [32]:
x = np.random.randint(1,25,(2,3))
y = np.random.randint(1,25,(3,2))
print(x)
print(y)

[[24 14 20]
 [ 3 17  7]]
[[ 6 24]
 [ 7 17]
 [14 13]]


In [33]:
y.T

array([[ 6,  7, 14],
       [24, 17, 13]])

In [34]:
print("x+y transposed")
print(x+y.T)
print("x transposed + y")
print(x.T+y)

x+y transposed
[[30 21 34]
 [27 34 20]]
x transposed + y
[[30 27]
 [21 34]
 [34 20]]


In [37]:
print("matrix multiplication elementwise")
print(x*y.T)
print("matrix multiplication")
print(x@y)

matrix multiplication elementwise
[[144  98 280]
 [ 72 289  91]]
matrix multiplication
[[ 522 1074]
 [ 235  452]]


In [38]:
np.hstack((x,x,x,x,x))

array([[24, 14, 20, 24, 14, 20, 24, 14, 20, 24, 14, 20, 24, 14, 20],
       [ 3, 17,  7,  3, 17,  7,  3, 17,  7,  3, 17,  7,  3, 17,  7]])

In [39]:
np.vstack((x,x,y.T))

array([[24, 14, 20],
       [ 3, 17,  7],
       [24, 14, 20],
       [ 3, 17,  7],
       [ 6,  7, 14],
       [24, 17, 13]])

In [43]:
print(x)
print("sum of all elements of x:",x.sum())
print("sum of all elements row wise:",x.sum(axis=1))
print("sum of all elements col wise:",x.sum(axis=0))
print("average of all elements:",x.mean())
print("average of all elements:",np.median(x))
print("min of all elements:",x.min())
print("max of all elements:",x.max())
print("std of all elements:",x.std())
print("variance of all elements:",x.var())
print("any item is non-zero:",x.any())
print("all item are non-zero:",x.all())

[[24 14 20]
 [ 3 17  7]]
sum of all elements of x: 85
sum of all elements row wise: [58 27]
sum of all elements col wise: [27 31 27]
average of all elements: 14.166666666666666
average of all elements: 15.5
min of all elements: 3
max of all elements: 24
std of all elements: 7.243771270700243
variance of all elements: 52.47222222222222
any item is non-zero: True
all item are non-zero: True


In [44]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [45]:
x

array([[24, 14, 20],
       [ 3, 17,  7]])

In [46]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[-0.9056  0.9906  0.9129]
 [ 0.1411 -0.9614  0.657 ]]
[[ 0.4242  0.1367  0.4081]
 [-0.99   -0.2752  0.7539]]
[[-2.1349  7.2446  2.2372]
 [-0.1425  3.4939  0.8714]]
