In [3]:
import numpy as np

In [4]:
# creating array with arrange function of numpy
a = np.arange(15) # single dimensional
print (a)
a = np.arange(15).reshape(3,5) # multi dimensional
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [5]:
# size of array
a.size

15

In [6]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [7]:
y = np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [8]:
print('shape:',x.shape)
print('num of dimensions:',x.ndim)
print('type of data:',x.dtype)
print("Y")
print('shape:',y.shape)
print('num of dimensions:',y.ndim)
print('type of data',y.dtype)

shape: (5,)
num of dimensions: 1
type of data: int32
Y
shape: (2, 3)
num of dimensions: 2
type of data int32


- arange
- linspace
- random.*
- eye
- ones
- zeros

In [9]:
np.set_printoptions(precision=4,suppress=True)

In [10]:
a = np.arange(-10,10,.2)
print(a)

[-10.   -9.8  -9.6  -9.4  -9.2  -9.   -8.8  -8.6  -8.4  -8.2  -8.   -7.8
  -7.6  -7.4  -7.2  -7.   -6.8  -6.6  -6.4  -6.2  -6.   -5.8  -5.6  -5.4
  -5.2  -5.   -4.8  -4.6  -4.4  -4.2  -4.   -3.8  -3.6  -3.4  -3.2  -3.
  -2.8  -2.6  -2.4  -2.2  -2.   -1.8  -1.6  -1.4  -1.2  -1.   -0.8  -0.6
  -0.4  -0.2  -0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8
   2.    2.2   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2
   4.4   4.6   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6
   6.8   7.    7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.
   9.2   9.4   9.6   9.8]


In [11]:
print(a.size)

100


In [12]:
b = np.linspace(0,1,10)
print(b)

[0.     0.1111 0.2222 0.3333 0.4444 0.5556 0.6667 0.7778 0.8889 1.    ]


In [13]:
np.random.random((3,3)) #random values between 0 and 1

array([[0.6229, 0.9615, 0.7482],
       [0.0295, 0.2563, 0.1488],
       [0.6118, 0.8419, 0.5087]])

In [14]:
np.random.randint(1,1000,(3,3)) # random values between start and end

array([[ 91, 131,  55],
       [212, 563, 914],
       [153, 402, 435]])

In [15]:
np.eye(5,dtype=int) # identity matrix
# for rotating use rot(angle)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [16]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Operations
- arithmatic
- statistical
- trignometric
- logical
- slicing
- filtering
- sorting

In [18]:
x = np.random.randint(1,25,(2,3))
y = np.random.randint(1,25,(3,2))
print(x)
print(y)

[[15 15 16]
 [ 3  2 14]]
[[ 1 23]
 [ 9 23]
 [ 1 13]]


In [19]:
y.T

array([[ 1,  9,  1],
       [23, 23, 13]])

In [20]:
print("x+y transposed")
print(x+y.T)
print("x transposed + y")
print(x.T+y)

x+y transposed
[[16 24 17]
 [26 25 27]]
x transposed + y
[[16 26]
 [24 25]
 [17 27]]


In [21]:
print("matrix multiplication elementwise")
print(x*y.T)
print("matrix multiplication")
print(x@y)

matrix multiplication elementwise
[[ 15 135  16]
 [ 69  46 182]]
matrix multiplication
[[166 898]
 [ 35 297]]


In [22]:
np.hstack((x,x,x,x,x))

array([[15, 15, 16, 15, 15, 16, 15, 15, 16, 15, 15, 16, 15, 15, 16],
       [ 3,  2, 14,  3,  2, 14,  3,  2, 14,  3,  2, 14,  3,  2, 14]])

In [23]:
np.vstack((x,x,y.T))

array([[15, 15, 16],
       [ 3,  2, 14],
       [15, 15, 16],
       [ 3,  2, 14],
       [ 1,  9,  1],
       [23, 23, 13]])

In [24]:
print(x)
print("sum of all elements of x:",x.sum())
print("sum of all elements row wise:",x.sum(axis=1))
print("sum of all elements col wise:",x.sum(axis=0))
print("average of all elements:",x.mean())
print("average of all elements:",np.median(x))
print("min of all elements:",x.min())
print("max of all elements:",x.max())
print("std of all elements:",x.std())
print("variance of all elements:",x.var())
print("any item is non-zero:",x.any())
print("all item are non-zero:",x.all())

[[15 15 16]
 [ 3  2 14]]
sum of all elements of x: 65
sum of all elements row wise: [46 19]
sum of all elements col wise: [18 17 30]
average of all elements: 10.833333333333334
average of all elements: 14.5
min of all elements: 2
max of all elements: 16
std of all elements: 5.927806414592913
variance of all elements: 35.138888888888886
any item is non-zero: True
all item are non-zero: True


In [25]:
print(np.pi)
print(np.nan)
print(np.inf)
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [26]:
x

array([[15, 15, 16],
       [ 3,  2, 14]])

In [27]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[[ 0.6503  0.6503 -0.2879]
 [ 0.1411  0.9093  0.9906]]
[[-0.7597 -0.7597 -0.9577]
 [-0.99   -0.4161  0.1367]]
[[-0.856  -0.856   0.3006]
 [-0.1425 -2.185   7.2446]]


Boolean filter

In [29]:
x[x > 5]

array([15, 15, 16, 14])

In [48]:
x = np.random.randint(-3,3, (5,5))
x

array([[ 1,  2,  0,  1, -2],
       [ 1, -1,  2, -1,  2],
       [-3,  1,  1,  2,  1],
       [ 1,  0,  0, -3, -1],
       [-1, -1,  1,  1, -2]])

In [49]:
x[(x>-2)&(x<2)]
#x[(x>-2)|(x<1)] for or

array([ 1,  0,  1,  1, -1, -1,  1,  1,  1,  1,  0,  0, -1, -1, -1,  1,  1])

### indexing and slicing

In [50]:
x[0,0]

1

In [51]:
print(x[0]) # first row 
print(x[-1]) # last row

[ 1  2  0  1 -2]
[-1 -1  1  1 -2]


- syntax for slicing in 1d:`[start:stop:step]`
- syntax for slicing in 2d:`[rstart:rstop:rstep , cstart:cstop:cstep]`

In [55]:
print(x[2,-4:]) # index row last four elements
print(x[0,:3]) # first row three elements

[1 1 2 1]
[1 2 0]


In [56]:
print(x[-1:]) # last row

[[-1 -1  1  1 -2]]


In [63]:
print(x[:,0]) # first column
print(x[:,-1]) # last column
print(x[:,:-2]) # first three columns
print(x[:,[1,3]]) # first index and third index column
print(x[:,[2,4,1,3]]) # 2,4,1,3 columns

[ 1  1 -3  1 -1]
[-2  2  1 -1 -2]
[[ 1  2  0]
 [ 1 -1  2]
 [-3  1  1]
 [ 1  0  0]
 [-1 -1  1]]
[[ 2  1]
 [-1 -1]
 [ 1  2]
 [ 0 -3]
 [-1  1]]
[[ 0 -2  2  1]
 [ 2  2 -1 -1]
 [ 1  1  1  2]
 [ 0 -1  0 -3]
 [ 1 -2 -1  1]]


### sorting

In [68]:
y = np.random.randint(1,100,(6,3))
y

array([[29, 43, 63],
       [73, 76, 41],
       [83, 17, 42],
       [98, 42, 31],
       [ 4, 49, 33],
       [ 7, 65, 81]])

In [71]:
y.sort(axis=0) # sort by column
y

array([[ 4, 17, 31],
       [ 7, 33, 42],
       [29, 41, 43],
       [42, 49, 73],
       [63, 65, 83],
       [76, 81, 98]])

In [72]:
y.sort(axis=1) # sort by row
y

array([[ 4, 17, 31],
       [ 7, 33, 42],
       [29, 41, 43],
       [42, 49, 73],
       [63, 65, 83],
       [76, 81, 98]])

In [75]:
y = y.flatten()
y.sort()
y

array([ 4,  7, 17, 29, 31, 33, 41, 42, 42, 43, 49, 63, 65, 73, 76, 81, 83,
       98])

In [77]:
x.max()

2

In [79]:
x.argmax() # returns index of max elemnet

21

In [80]:
x.argmin() # returns index of min element

0